[package]
name = "neko-bench"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neko-wire = { path = "../neko-wire" }
neko-crypto = { path = "../neko-crypto" }
neko-carrier = { path = "../neko-carrier" }
neko-reliable = { path = "../neko-reliable" }

[lints]
workspace = true
