[package]
name = "neko-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
neko-crypto = { path = "../neko-crypto" }
neko-wire = { path = "../neko-wire" }
neko-carrier = { path = "../neko-carrier" }
neko-session = { path = "../neko-session" }
signal-hook = "0.3"
sha2 = "0.10"

[lints]
workspace = true
